name: Build site

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      working-directory: ./src/FuncInfrastructureAsCode.Client
      run: npm ci
    
    - name: Build project
      working-directory: ./src/FuncInfrastructureAsCode.Client
      run: npm run build

    - name: check path1
      run: ls -lisa

    - name: check path2
      run: ls -lisa ./src

    - name: check path3
      run: ls -lisa ./src/FuncInfrastructureAsCode.Client

    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: print
      uses: azure/CLI@v1
      with:
        inlineScript: ls -lisa

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name funcinfrastructureascode --auth-mode key -d 'client' -s './src/FuncInfrastructureAsCode.Client/build/*'

# Azure logout
    - name: logout
      run: |
            az logout
      if: always()